name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build ./FizzBuzz.Web/FizzBuzz.Web.csproj -c Release

    - name: Publish
      run: dotnet publish ./FizzBuzz.Web/FizzBuzz.Web.csproj -c Release -o publish_output

    # - name: List publish output (for debug)
    #   run: ls -R publish_output

    # - name: Zip Publish Directory (flatten)
    #   run: cd publish_output && zip -r ../publish_output.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: webapp-modern
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish_output/
